@startuml

'fixes empty description error
skinparam monochrome false

!define COLOR_0    #56a9e8
!define COLOR_1       #a7dbd7
!define COLOR_2   #e0e4cc
!define COLOR_3     #f38631
!define COLOR_4    #fa6900
!define COLOR_5 #fa2700
!define COLOR_NATIVE_CONTAINER    #LightGreen
!define COLOR_WEB    #LightGreen
!define COLOR_NETWORK    #white

!definelong USE_COLOR_BACKGROUND
    skinparam rectangle {
            BackgroundColor COLOR_BACKGROUND
            }
!enddefinelong

!define BOLD(x) **x**

@enduml