@startuml
'===============CONFIGURATION_START=============='

!define COLOR_0    #fad089
!define COLOR_1       #ff9c5b
!define COLOR_2   #4e9092
!define COLOR_3     #f5634a
!define COLOR_4    #ec303c
!define COLOR_5 #2e6c8c
!define COLOR_NATIVE_CONTAINER    #LightGreen
!define COLOR_WEB    #428b98
!define COLOR_NETWORK    #white
!define COLOR_BACKGROUND    #d1dbde

!definelong USE_COLOR_BACKGROUND
    skinparam rectangle {
            BackgroundColor COLOR_BACKGROUND
            }
!enddefinelong

!define BOLD(x) **x**
'===============CONFIGURATION_ENDS==============='


'================CONTAINERS_START=============='
rectangle "Root - Version:  #CHANGE_VERSION_NUMBER" COLOR_BACKGROUND{

        rectangle "Root" COLOR_WEB {
        rectangle "My Machine" as ROOT
        rectangle "Terminal" as Terminal
      }

        rectangle "Network" as networkLayer COLOR_NETWORK {
            #REPLACE_WITH_CONTAINERS_HERE
     }
}
'================CONTAINERS_ENDS=============='



'==============RELATIONS_START================'
ROOT --> Terminal
Terminal <---> networkLayer

#CHANGE_RELATIONS

'==============RELATIONS_ENDS================'


@enduml
