version: '2.1'
services:
  elastic:
    image: elasticsearch:5.6.3
    container_name: testing
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 11200:9200
      - 11300:9300
    volumes:
      - elastic_data:/usr
    healthcheck:
      test: "curl -sS http://localhost:9200/"
      interval: 1s
      timeout: 60s
      retries: 120
  app:
    build: .
    environment:
    - "ES_JAVA_OPTS=-dummy -Xmx512m"
    ports:
    - 11200:9200
    - 11300:9300
    volumes:
    - dummytext
    healthcheck:
      test: "curl -sS http://localhost:9200/"
      interval: 1s
  redis:
    image: redis
    environment:
    - "ES_JAVA_OPTS=-dumy -Xmx512m"
    ports:
    - 11200:9200
    - 11300:9300
    volumes:
    - dummytext
    healthcheck:
      test: "curl -sS http://localhost:9200/"
      interval: 1s
