@startuml

!include ../global/G_Consts.puml
/'!include Global/G_Macros.puml
!include Global/G_Client.puml
!include Global/G_Oracle.puml'/

USE_COLOR_BACKGROUND


'Objects'
'=============================='
rectangle "Model Management"{

	rectangle "Sma Web" COLOR_WEB{
		rectangle "VehicleModelResource" as vehicleModelResource
		rectangle "EcuModelResource" as ecuModelResource
		rectangle "DeviceClassResource" as deviceClassResource
	}

    rectangle "Sma Services" as SmaRes COLOR_SERVICE {

            'VehicleModel Management
            '=======================
    		rectangle "VehicleModelFacadeBean" as vehicleModelFacadeBean
    		rectangle "VehicleModelServiceBean" as vehicleModelServiceBean
    		rectangle "VehicleModelConverter" as VehicleModelConverter

            'EcuModel Management
            '=======================
    		rectangle "EcuModelFacadeBean" as ecuModelFacadeBean
            rectangle "EcuModelServiceBean" as ecuModelServiceBean
            rectangle "EcuModelConverter" as ecuModelConverter

            'DeviceModel Management
            '=======================
            rectangle "DeviceClassFacadeBean" as deviceClassFacadeBean
    		rectangle "DeviceClassServiceBean" as deviceClassServiceBean
    		rectangle "DeviceClassConverter" as deviceClassConverter

    	}

	rectangle "Sma Utils" as SmaUtils COLOR_SMA_UTILS {
	    rectangle "VehicleModelDao" as vehicleModelDao
	    rectangle "EcuModelDao" as ecuModelDao
	    rectangle "DeviceClassDao" as deviceClassDao
	}

}

''
'Relations
'==============================
client --> vehicleModelResource
client --> ecuModelResource
client --> deviceClassResource

vehicleModelResource --> vehicleModelFacadeBean
ecuModelResource --> ecuModelFacadeBean
deviceClassResource --> deviceClassFacadeBean


vehicleModelFacadeBean --> vehicleModelServiceBean
vehicleModelFacadeBean --> VehicleModelConverter
VehicleModelConverter --> vehicleModelDao
vehicleModelFacadeBean --> deviceClassServiceBean
ecuModelFacadeBean --> ecuModelServiceBean
ecuModelFacadeBean --> ecuModelConverter
ecuModelConverter --> ecuModelDao
ecuModelFacadeBean --> deviceClassServiceBean
deviceClassFacadeBean --> deviceClassConverter
deviceClassFacadeBean --> deviceClassServiceBean

vehicleModelServiceBean --> vehicleModelDao
ecuModelServiceBean --> ecuModelDao
deviceClassServiceBean --> deviceClassDao

vehicleModelDao --> oracle
ecuModelDao --> oracle
deviceClassDao --> oracle


@enduml
